### ISSUE TITLE
Demo?

### ISSUE THREAD

**Issue by prologic** [inmagik/registryo#1]
Is there a demo of this or screenshots?

Can we add OAuth integration against Gitea?

**Comment by osioalberto** [comment]
Hi @prologic, we have [a nice blog post](https://inmagik.com/blog/private-docker-registry) on our website with details and some screenshots, you can check it out if you want. Moreover, I just pushed some screenshots in the `screenshots` folder of this same repository.

Talking about Gitea integration, feel free to implement it and open a pull request! It would be nice to have some OAuth integrations.

**Comment by prologic** [comment]
Thanks! I'll check it out!
